### ISSUE TITLE
Can't get the code

### ISSUE THREAD

**Issue by eruizman** [andrea-mattioli/bticino_x8000_docker#1]
Hi Andrea,  i've a X8000 thermostat by Bticino, model Smarther1, controled by Thermostat app. I've installed your rep, make the api at Legrand... and I arrive up to give permision to Home_user, and is this step I've the follow error 500, see atached images
i've tried changing the host, but it gave me another error. 
I don't know what more to do... If you need any log or something, ask me... I'm totally lost...
thanks.
ESteban Ruiz
![photo_2021-04-10_13-34-16](https://user-images.githubusercontent.com/81024085/114268531-d38fe600-9a01-11eb-9b60-f3a767d5a86c.jpg)
![photo_2021-04-10_13-34-37](https://user-images.githubusercontent.com/81024085/114268533-d4287c80-9a01-11eb-954b-2a61573e6fcc.jpg)
![photo_2021-04-10_13-35-18](https://user-images.githubusercontent.com/81024085/114268534-d4287c80-9a01-11eb-91e5-8c4eb69b4fee.jpg)

**Comment by andrea-mattioli** [comment]
Hi try to use the internal ip address: http://192.168.1.114:5588 
If you are using duckdns and you must have only https also in local IP, please use my "mattiols reverse proxy" to avoid this problem.

**Comment by eruizman** [comment]
Hi Andrea,

I've the HA connected to a second router by ethernet cable (mesh wifi
router). It gives me the IP domain 192.168.1.*** for wifi

on the main router I have this:

[image: imagen.png]

also on the second router i have forward the same ports as well.

On the legrad api, now I've on first url reply the IP as you have suggested
me, let's see if it works.

[image: imagen.png]


[image: imagen.png]


after click on the button to permit access to home user it goes to the
follow address with error:

[image: imagen.png]
and if I change  manually to http://
[image: imagen.png]
I've no idea what more I can do....

Thanks for your help.

Esteban Ruiz

**Comment by eruizman** [comment]
The missing images on the previous post...
![unnamed](https://user-images.githubusercontent.com/81024085/114858967-6a85e500-9dea-11eb-902f-4f7a3886c690.png)
![unnamed1](https://user-images.githubusercontent.com/81024085/114858969-6b1e7b80-9dea-11eb-83ff-89cca76db973.png)
![unnamed2](https://user-images.githubusercontent.com/81024085/114858973-6bb71200-9dea-11eb-86b1-31476fe9ea72.png)
![unnamed3](https://user-images.githubusercontent.com/81024085/114858975-6bb71200-9dea-11eb-89e9-30470a9d0416.png)
![unnamed4](https://user-images.githubusercontent.com/81024085/114858976-6c4fa880-9dea-11eb-9eeb-6f53253de674.png)
![unnamed5](https://user-images.githubusercontent.com/81024085/114858978-6c4fa880-9dea-11eb-8abf-115f1305f424.png)

**Comment by andrea-mattioli** [comment]
hi you must use V2 addon and remove the nat on 5588

**Comment by eruizman** [comment]
Hi, I've desinstaled first addon and install V2, but same error at the
end...
Internal Server Error.
If I send to you the log of the addon can it help?

**Comment by eruizman** [comment]
This is the register log from addon:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[17:36:29] INFO: Smarter file already exist and contain some data.
[17:36:29] INFO: Setup config file...
 * Serving Flask app "bticino" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a
production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5588/ (Press CTRL+C to quit)
192.168.1.115 - - [15/Apr/2021 17:39:18] "GET / HTTP/1.1" 200 -
192.168.1.115 - - [15/Apr/2021 17:39:19] "GET /favicon.ico HTTP/1.1" 404 -
[2021-04-15 17:39:32,832] ERROR in app: Exception on /callback [GET]
Traceback (most recent call last):
  File "bticino.py", line 299, in get_plants
    plants = json.loads(response.text)['plants']
KeyError: 'plants'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1951, in
full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1820, in
handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1949, in
full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1935, in
dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "bticino.py", line 744, in callback
    my_plants=get_plants(access_token)
  File "bticino.py", line 307, in get_plants
    print("[Errno {0}] {1}".format(e.errno, e.strerror))
AttributeError: 'KeyError' object has no attribute 'errno'
192.168.1.115 - - [15/Apr/2021 17:39:32] "GET
/callback?code=eyJraWQiOiJjcGltY29yZV8wOTI1MjAxNSIsInZlciI6IjEuMCIsInppcCI6IkRlZmxhdGUiLCJzZXIiOiIxLjAifQ..EcmuCANxvkxiINWE.rna9LKa4A646sSbTfL6bzvNbDks27AoRRAF7H_xmmw3ua6Ogausnj39ZAm9Asz8qsu8XUt2q4TJufoqjKFBceCCSydU6ccSljHIO_jkA_cQidthBHTUG662hnZIew-hU-t2kM0OEf4Coifzq3b3HMMWW8s53TRR1-85suyCiUnLbkbAbDbfZLco0wWRo_uuIBafYF-GYrP4sfebLpmuboo5vm440h__hm4AakQq6Fp37FmaKb10FMWG-_IYgJxrvkDmZP8yJFsMUBv7kaIUwppXkZVg35HtvyINT9sxrLwb2-hSmU1zDie_Zhp2P5G31y-rIaUP4dXvnj8e73LFkyxM4F0bNDrKkjq3Zc42_DGPC2-gK9Y0augIIlcFkslmmb9TBfi6tsFzWxSTepMAkDmFbMTz9To3ryPLcyLzZjjDOtGTKEPEj5REn3WUcZ30V0Xy89rYPvbS3IaUsUX_L-Tw2BHoY7eppb0IBeSsqR3qpCh7rFOVTuxZVg1z3JS_K_YFGGiXl1vyKwYB-ng8ghELeaYWcrujx4tTQ2Iw3j8J8iKZrJgGO7uvZVTE13sCccL9FHJIbaWTh9NstapekwWdP0ap_KeQohKtrbbP_exvUZcBGcY4Wuof5P1mMgPiMmhm0vqZJ8rFaLqGQ9wauq-uhHCF_v2J1uaifKQoz1pqR2oWSBlFPNYDjfNCiyUgO_mV0o0RX4DiyUkDFmh-DhkO4cvq0bxzyqqLsggq9t2gEW624ePsvHk5anUe5Io3LeWVBn0cNo6X_il2vr50jqigawhGlcqgsA5FaNMw6Ob74b9P0sKG-aRkirIFovUNqEvdKmpiKrwEiCmX9MgzwYbLRSfRShcfJk8r-rgdhtZsO4wrkYUo.lpFRbh7d0mYF_Kp0FzOA1Q&state=oKABUnYykTBcG78S5cwiCWm7cHhUwubR
HTTP/1.1" 500 -

**Comment by andrea-mattioli** [comment]
open terminal and run the following command:
`rm -rf .bticino_smarter/*`

then restart the addon and open another browser window to http://192.168.1.14:5588 (you must use HTTP not HTTPS)

**Comment by eruizman** [comment]
I've deleted .bticino_smarter on config folder with the command you
suggested.
Then i restarted the addon, and before open the browser i get the following
message

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[11:10:39] INFO: Smarter file already exist and contain some data.
[11:10:39] INFO: Setup config file...
 * Serving Flask app "bticino" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a
production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5588/ (Press CTRL+C to quit)

Then I open the http://192.168.1.114:5588 and after click on give
permission the same error 500

192.168.1.115 - - [16/Apr/2021 11:11:57] "GET / HTTP/1.1" 200 -
[2021-04-16 11:12:31,992] ERROR in app: Exception on /callback [GET]
Traceback (most recent call last):
  File "bticino.py", line 299, in get_plants
    plants = json.loads(response.text)['plants']
KeyError: 'plants'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1951, in
full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1820, in
handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1949, in
full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.8/site-packages/flask/app.py", line 1935, in
dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "bticino.py", line 744, in callback
    my_plants=get_plants(access_token)
  File "bticino.py", line 307, in get_plants
    print("[Errno {0}] {1}".format(e.errno, e.strerror))
AttributeError: 'KeyError' object has no attribute 'errno'
192.168.1.115 - - [16/Apr/2021 11:12:32] "GET
/callback?code=eyJraWQiOiJjcGltY29yZV8wOTI1MjAxNSIsInZlciI6IjEuMCIsInppcCI6IkRlZmxhdGUiLCJzZXIiOiIxLjAifQ..8XdwcOYniIo8PiRX.1LWVT3sSbzs3jZ9_BJbKDO-ZmwM6QEOoNjXeQgUeuDmgWyudV9MiGjBn0D-mP8lGkdRkAtHbrqZqFEZpuu1ytGANw4ZG_pYGYqGrJ4xZ2PqlPC0-Mxp1wCbxPWzzKQLTwwxy22oQ87pX8gwHura1GE7EcVsdrPXm9myP2fpXaVs5XYbDdmXTgAW8tgB2A8ctJDr2FGskqNBuSTq08ph1wCoKpVX-SsMGiWAdSX9XtOEwzJAt5VPDuktZPlJUUrvc-reEW-URXehu-HLvduMWt1u7g7PVKl_BzOYzeZdyeFNVpc_FX7vgRh2_Sp7b2m7yRUZWgp024awga_V0LhYjF68CNa-K5yWIPU8_ww905Kp-eaFb6mHegg--hYW3nfZZ00zBevFxrFl1T0BFd9p6ezFqGB2cbFHflPJ0b2eOFcf5nOuEE1d5pUzekw1TcFEb-fUI_lg4nTOEPLZn8wF9ojtyaN-76OM60gDZfFzUK_swB1eSR3x4UiZg-whfYJht3-gs_f__9Kli_5-8gAtZOkeA0bDVoj51SwWgX7IFkOqI2WzW_6MABwul4Fa30MaHKmU1nqtIlW4FhXp44F0UFFLanH1uM6pP1RxFxSI7FXiIAfTkGKNZHNzS04wg7CndSs2nDZsNpZq5j8yWX3phg6jg_ZnPaVqS5XXe1pRXDr-SiFfNxY1w3_0oZJUlk_f3IdP35hgIf1pkU3fnC-gGFiQfCAsMgNqas137jyAuiOrUOiqgwQ-ppTcuRlcBxRexbZaYpMLeXoC6zJ1k5gSeTMt55OnxZcA-Q_zsVCum8lzmj6pT4-qXxVL7EmcKZetlQIL5TLkOdRbemTg7xcFiZx0ZsYC5OAmQeOlthTXK_RrPHNeh.845BnhP2PWvidp3xBGe7Dg&state=Bm7GgYE1JHyWJpS47r7u4k5yJYt2ctlx
HTTP/1.1" 500 -

**Comment by andrea-mattioli** [comment]
hmm something went wrong after the rm of config data why addon says "[11:10:39] INFO: Smarter file already exist and contain some data" could we schedule a remote session?
try to remove .bticino_smarter again and rebuild the addon (v2)

**Comment by eruizman** [comment]
I've delete again the file,  rebuild the addon, start it..and without open
the browser this is the output

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[13:04:41] INFO: Init Smarter file ...
[13:04:41] INFO: 64bit Version detected
[13:04:41] INFO: Setup config file...
[13:04:45] INFO: Trying autologin to Legrand...
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/selenium/webdriver/common/service.py",
line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1706, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'chromedriver'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "login.py", line 20, in <module>
    driver = webdriver.Chrome(options=chrome_options)
  File "/usr/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py",
line 73, in __init__
    self.service.start()
  File "/usr/lib/python3.8/site-packages/selenium/webdriver/common/service.py",
line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver'
executable needs to be in PATH. Please see
https://sites.google.com/a/chromium.org/chromedriver/home
[cmd] /hassio_bticino_smarter/run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
s6-svwait: fatal: unable to subscribe to events for
/var/run/s6/services/s6-fdholderd: Operation timed out
[s6-finish] sending all processes the TERM signal.

**Comment by eruizman** [comment]
if I stop/start the addon this is the second output:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[13:07:04] INFO: Smarter file already exist and contain some data.
[13:07:04] INFO: Setup config file...
 * Serving Flask app "bticino" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a
production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://0.0.0.0:5588/ (Press CTRL+C to quit)

**Comment by eruizman** [comment]
we can do a remote session if you want, at what time?

**Comment by andrea-mattioli** [comment]
Now?
i send you a google meet 
To join the video meeting, click this link: https://meet.google.com/bns-pjjw-crs

**Comment by eruizman** [comment]
I,ve seen your mail now... can be at 17.00?

**Comment by andrea-mattioli** [comment]
ok i'm already connect on meet
